version: '3'
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_PID: "Developer"
      SA_PASSWORD: "SqlServer?!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"